{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "NavFromMobileSalesPageToMobileSalesDocumentPage"
	},
	"PageToOpen": "/LMD_MDKApp/Pages/MyVisit/MobileSalesDocument.page",
	"ModalPage": true
}