{
	"_Type": "Action.Type.BannerMessage",
	"ActionResult": {
		"_Name": "ReloadSaveStatusBanner"
	},
	"Message": "/LMD_MDKApp/Rules/ReloadCheckIn/BuildReloadSaveStatusMessage.js",
	"Duration": 10,
	"Animated": true
}