{
	"_Type": "Action.Type.PopoverMenu",
	"PopoverItems": [
		{
			"Enabled": true,
			"Icon": "sap-icon://synchronize",
			"OnPress": "/LMD_MDKApp/Actions/LMD_MA/Service/SyncStartedMessage.action",
			"Title": "Sync Changes",
			"Visible": "$(PLT,true,true,false)"
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://headset",
			"OnPress": "/LMD_MDKApp/Actions/Application/NavToSupport.action",
			"Title": "Support",
			"Visible": true
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://refresh",
			"OnPress": "/LMD_MDKApp/Actions/Application/AppUpdateProgressBanner.action",
			"Title": "Check for Updates",
			"Visible": "$(PLT,true,true,false)"
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://hint",
			"OnPress": "/LMD_MDKApp/Actions/Application/NavToAbout.action",
			"Title": "About",
			"Visible": true
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://reset",
			"OnPress": "/LMD_MDKApp/Actions/Application/ResetMessage.action",
			"Title": "Reset",
			"Visible": true
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://log",
			"OnPress": "/LMD_MDKApp/Actions/Application/Logout.action",
			"Title": "Logout",
			"Visible": "/LMD_MDKApp/Rules/Application/ClientIsMultiUserMode.js"
		},
		{
			"Title": "Transfer",
			"Icon": "sap-icon://forward",
			"OnPress": "/LMD_MDKApp/Actions/TruckTransfer/RouteStartDateTimeUpdate_OnTransfer.action",
			"Visible": true,
			"Enabled": true,
			"Styles.Title": "",
			"Styles.Icon": ""
		},
		{
			"Title": "Receive",
			"Icon": "sap-icon://inbox",
			"Visible": true,
			"Enabled": true,
			"Styles.Title": "",
			"Styles.Icon": ""
		},
		{
			"Title": "Download Data ",
			"Icon": "sap-icon://download",
			"Styles": {
				"Title": "",
				"Icon": ""
			},
			"OnPress": "/LMD_MDKApp/Actions/API_LASTMILERELOADREQUEST/ReInitialize.action",
			"Visible": true,
			"Enabled": true
		}
	]
}