{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "NavBackToCheckoutFromConfirmTruckInfo"
	},
	"OnSuccess": "/LMD_MDKApp/Actions/StartCheckout/TruckLoad/OdometerBeginUpdated.action",
	"PageToOpen": "/LMD_MDKApp/Pages/ StartCheckout/Checkout.page"
}