{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "UpdateOdometerBegin"
	},
	"OnFailure": "/LMD_MDKApp/Actions/StartCheckout/OdometerFailure.action",
	"Target": {
		"Service": "/LMD_MDKApp/Services/DEST_SAMSMA_PPROP.service",
		"EntitySet": "Routes",
		"ReadLink": "/LMD_MDKApp/Rules/Checkout/TruckInfo/UpdateOdometerBeginReadLink.js"
	},
	"Properties": {
		"OdometerBegin": "{#Control:OdometerBeginInput/#Value}"
	},
	"Headers": {
		"BatchGroup": "RouteStopBatch"
	}
}