{
	"_Type": "Action.Type.OfflineOData.Download",
	"ActionResult": {
		"_Name": "sync"
	},
	"OnFailure": "/LMD_MDKApp/Actions/DEST_SAMSMA_PPROP/Service/SyncFailureMessage.action",
	"OnSuccess": "/LMD_MDKApp/Rules/DEST_SAMSMA_PPROP/ErrorArchive_CheckForSyncError.js",
	"Service": "/LMD_MDKApp/Services/DEST_SAMSMA_PPROP.service",
	"DefiningRequests": [
		{
			"Name": "Attachments",
			"Query": "Attachments"
		},
		{
			"Name": "BankDeposits",
			"Query": "BankDeposits"
		},
		{
			"Name": "CociBehaviors",
			"Query": "CociBehaviors"
		},
		{
			"Name": "COCIPayments",
			"Query": "COCIPayments"
		},
		{
			"Name": "CollectionClearings",
			"Query": "CollectionClearings"
		},
		{
			"Name": "CollectionPayments",
			"Query": "CollectionPayments"
		},
		{
			"Name": "Collections",
			"Query": "Collections"
		},
		{
			"Name": "Contents",
			"Query": "Contents"
		},
		{
			"Name": "DepositAccountReferences",
			"Query": "DepositAccountReferences"
		},
		{
			"Name": "DocumentItemConditions",
			"Query": "DocumentItemConditions"
		},
		{
			"Name": "DocumentItems",
			"Query": "DocumentItems"
		},
		{
			"Name": "Documents",
			"Query": "Documents"
		},
		{
			"Name": "DriverLanguages",
			"Query": "DriverLanguages"
		},
		{
			"Name": "InventoryGroups",
			"Query": "InventoryGroups"
		},
		{
			"Name": "MaterialTypeInventoryGroups",
			"Query": "MaterialTypeInventoryGroups"
		},
		{
			"Name": "MobileClientSynchronizationSessions",
			"Query": "MobileClientSynchronizationSessions"
		},
		{
			"Name": "MobileDocumentTypes",
			"Query": "MobileDocumentTypes"
		},
		{
			"Name": "MobileNumberRanges",
			"Query": "MobileNumberRanges"
		},
		{
			"Name": "MobileSalesDocumentItems",
			"Query": "MobileSalesDocumentItems"
		},
		{
			"Name": "MobileSalesDocuments",
			"Query": "MobileSalesDocuments"
		},
		{
			"Name": "OpenItems",
			"Query": "OpenItems"
		},
		{
			"Name": "ReasonCodes",
			"Query": "ReasonCodes"
		},
		{
			"Name": "ReasonCodeUsages",
			"Query": "ReasonCodeUsages"
		},
		{
			"Name": "Routes",
			"Query": "Routes"
		},
		{
			"Name": "RouteTypes",
			"Query": "RouteTypes"
		},
		{
			"Name": "ServiceTasks",
			"Query": "ServiceTasks"
		},
		{
			"Name": "Stops",
			"Query": "Stops"
		},
		{
			"Name": "Texts",
			"Query": "Texts"
		},
		{
			"Name": "AppParams",
			"Query": "AppParams",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "BusinessPartners",
			"Query": "BusinessPartners",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "DriverTrackingConfigurations",
			"Query": "DriverTrackingConfigurations",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "HTMLTemplates",
			"Query": "HTMLTemplates",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "DriverGroupTemplateMappings",
			"Query": "DriverGroupTemplateMappings",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "PaymentTypes",
			"Query": "PaymentTypes",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "ItemCategorySet",
			"Query": "ItemCategorySet",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "SalesOrderTypes",
			"Query": "SalesOrderTypes",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "Products",
			"Query": "Products",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "ProductSales",
			"Query": "ProductSales",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "ProductUOMs",
			"Query": "ProductUOMs",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "COCIProducts",
			"Query": "COCIProducts",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "Customers",
			"Query": "Customers",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "CustomerBillingData",
			"Query": "CustomerBillingData",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "CustomerPaymentMethods",
			"Query": "CustomerPaymentMethods",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "CustomerSalesData",
			"Query": "CustomerSalesData",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "Addresses",
			"Query": "Addresses",
			"AutomaticallyRetrievesStreams": false
		}
	]
}