{
	"_Type": "Action.Type.ODataService.Initialize",
	"ActionResult": {
		"_Name": "init"
	},
	"OnFailure": "/LMD_MDKApp/Actions/DEST_SAMSMA_PPROP/Service/InitializeOfflineFailureMessage.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Downloading...",
	"Service": "/LMD_MDKApp/Services/DEST_SAMSMA_PPROP.service",
	"DefiningRequests": [
		{
			"Name": "Attachments",
			"Query": "Attachments"
		},
		{
			"Name": "BankDeposits",
			"Query": "BankDeposits"
		},
		{
			"Name": "CociBehaviors",
			"Query": "CociBehaviors"
		},
		{
			"Name": "COCIPayments",
			"Query": "COCIPayments"
		},
		{
			"Name": "CollectionClearings",
			"Query": "CollectionClearings"
		},
		{
			"Name": "CollectionPayments",
			"Query": "CollectionPayments"
		},
		{
			"Name": "Collections",
			"Query": "Collections"
		},
		{
			"Name": "Contents",
			"Query": "Contents"
		},
		{
			"Name": "DepositAccountReferences",
			"Query": "DepositAccountReferences"
		},
		{
			"Name": "DocumentItemConditions",
			"Query": "DocumentItemConditions"
		},
		{
			"Name": "DocumentItems",
			"Query": "DocumentItems"
		},
		{
			"Name": "DriverLanguages",
			"Query": "DriverLanguages"
		},
		{
			"Name": "InventoryGroups",
			"Query": "InventoryGroups"
		},
		{
			"Name": "MaterialTypeInventoryGroups",
			"Query": "MaterialTypeInventoryGroups"
		},
		{
			"Name": "MobileSalesDocuments",
			"Query": "MobileSalesDocuments"
		},
		{
			"Name": "OpenItems",
			"Query": "OpenItems"
		},
		{
			"Name": "ReasonCodes",
			"Query": "ReasonCodes"
		},
		{
			"Name": "ReasonCodeUsages",
			"Query": "ReasonCodeUsages"
		},
		{
			"Name": "Routes",
			"Query": "Routes"
		},
		{
			"Name": "RouteTypes",
			"Query": "RouteTypes"
		},
		{
			"Name": "ServiceTasks",
			"Query": "ServiceTasks"
		},
		{
			"Name": "Stops",
			"Query": "Stops"
		},
		{
			"Name": "Texts",
			"Query": "Texts"
		},
		{
			"Name": "AppParams",
			"Query": "AppParams",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "BusinessPartners",
			"Query": "BusinessPartners",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "DriverTrackingConfigurations",
			"Query": "DriverTrackingConfigurations",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "HTMLTemplates",
			"Query": "HTMLTemplates",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "DriverGroupTemplateMappings",
			"Query": "DriverGroupTemplateMappings",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "PaymentTypes",
			"Query": "PaymentTypes",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "PaymentTypes",
			"Query": "PaymentTypes",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "Products",
			"Query": "Products",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "ProductUOMs",
			"Query": "ProductUOMs",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "COCIProducts",
			"Query": "COCIProducts",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "Customers",
			"Query": "Customers",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "Addresses",
			"Query": "Addresses",
			"AutomaticallyRetrievesStreams": false
		}
	]
}