{
	"_Type": "Action.Type.OfflineOData.Upload",
	"ActionResult": {
		"_Name": "sync"
	},
	"OnFailure": "/LMD_MDKApp/Actions/DEST_SAMSMA_PPROP/Service/SyncFailureMessage.action",
	"OnSuccess": "/LMD_MDKApp/Actions/DEST_SAMSMA_PPROP/Service/DownloadStartedMessage.action",
	"Service": "/LMD_MDKApp/Services/DEST_SAMSMA_PPROP.service"
}