{
    "Service": "/LMD_MDKApp/Services/API_LASTMILEVISITLIST.service",
    "DefiningRequests": [{
            "Name": "CustomerDelivery",
            "Query": "CustomerDelivery"
        },
        {
            "Name": "LoadProposal",
            "Query": "LoadProposal"
        },
        {
            "Name": "LoadProposalProduct",
            "Query": "LoadProposalProduct"
        },
        {
            "Name": "Visit",
            "Query": "Visit"
        },
        {
            "Name": "VisitItem",
            "Query": "VisitItem"
        },
        {
            "Name": "VisitList",
            "Query": "VisitList"
        }
    ],
    "_Type": "Action.Type.OfflineOData.Download",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnFailure": "/LMD_MDKApp/Actions/API_LASTMILEVISITLIST/Service/SyncFailureMessage.action",
    "OnSuccess": "/LMD_MDKApp/Rules/API_LASTMILEVISITLIST/ErrorArchive_CheckForSyncError.js"
}