{
    "Message": "Upload in progress...",
    "CompletionMessage": "Sync completed",
    "CompletionTimeout": 7,
    "OnSuccess": "/LMD_MDKApp/Actions/API_LASTMILEVISITLIST/Service/UploadOffline.action",
    "OnFailure": "/LMD_MDKApp/Actions/API_LASTMILEVISITLIST/Service/SyncFailureMessage.action",
    "_Type": "Action.Type.ProgressBanner"
}