{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "StartDateTime"
	},
	"Target": {
		"Service": "/LMD_MDKApp/Services/LMD_MA.service",
		"EntitySet": "Stops",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"StartDateTime": "/LMD_MDKApp/Rules/Checkout/TruckInfo/GetLastChangeTimeStamp.js"
	},
	"Headers": {
		"OfflineOData.TransactionID": "#Property:RouteUUID"
	},
	"RequestOptions": {
		"UpdateMode": "Merge"
	}
}