{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "UpdateStopsChangesetFailure"
	},
	"Message": "{#ActionResults:UpdateStopsChangeset/error}",
	"Title": "{ErrorATStopsChangeset}",
	"OKCaption": "Ok"
}