{
    "_Type": "Action.Type.OfflineOData.Close",
    "Service": "/LMD_MDKApp/Services/DEST_SAMLMD_PPROP.service",
    "Force": true,
    "ActionResult": {
        "_Name": "close"
    },
    "OnSuccess": "/LMD_MDKApp/Actions/DEST_SAMLMD_PPROP/Service/CloseOfflineSuccessMessage.action",
    "OnFailure": "/LMD_MDKApp/Actions/DEST_SAMLMD_PPROP/Service/CloseOfflineFailureMessage.action"
}