{
    "Service": "/LMD_MDKApp/Services/DEST_SAMLMD_PPROP.service",
    "_Type": "Action.Type.OfflineOData.Upload",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnSuccess": "/LMD_MDKApp/Actions/DEST_SAMLMD_PPROP/Service/DownloadStartedMessage.action",
    "OnFailure": "/LMD_MDKApp/Actions/DEST_SAMLMD_PPROP/Service/SyncFailureMessage.action"
}