{
	"_Type": "Action.Type.ODataService.ChangeSet",
	"ActionResult": {
		"_Name": "UpdateOdometerChangeSet_Begin"
	},
	"OnFailure": "/LMD_MDKApp/Actions/StartCheckout/UpdateOdometerChangeSet_BeginFailure.action",
	"OnSuccess": "/LMD_MDKApp/Actions/StartCheckout/UpdateOdometerChangeSet_BeginSuccess.action",
	"Target": {
		"Service": "/LMD_MDKApp/Services/DEST_SAMLMD_PPROP.service"
	},
	"Actions": [
		"/LMD_MDKApp/Actions/StartCheckout/UpdateOdometerBegin.action"
	]
}