{
	"_Type": "Action.Type.ODataService.Read",
	"ActionResult": {
		"_Name": "ReadDepositAccountReferences"
	},
	"Target": {
		"Service": "/LMD_MDKApp/Services/LMD_MA.service",
		"EntitySet": "DepositAccountReferences"
	},
	"Properties": [
		"DepositAccountReferenceID",
		"Language",
		"Description"
	]
}