{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "CompleteVisit"
	},
	"OnSuccess": "/LMD_MDKApp/Actions/StartMyVisit/NavToVisitToMainPage.action",
	"PageToOpen": "/LMD_MDKApp/Pages/Main.page"
}