{
	"_Type": "Action.Type.ODataService.DownloadMedia",
	"ActionResult": {
		"_Name": "DownloadAttachment"
	},
	"OnFailure": "/LMD_MDKApp/Actions/StartMyVisit/ProofOfDelivery/DownloadAttachmentFailure.action",
	"Target": {
		"Service": "/LMD_MDKApp/Services/LMD_MA.service",
		"EntitySet": "Contents",
		"ReadLink": "{@odata.readLink}"
	},
	"DownloadResult": "DownloadedFile"
	
	
}