{
	"_Type": "Action.Type.OpenDocument",
	"ActionResult": {
		"_Name": "OpenDownload"
	},
	"OnFailure": "/LMD_MDKApp/Actions/StartMyVisit/ProofOfDelivery/Failure.action",
	"OnSuccess": "/LMD_MDKApp/Actions/StartMyVisit/ProofOfDelivery/Successfully_Created.action",
	"Path": "{@odata.mediaReadLink}",
	"MimeType": "/LMD_MDKApp/Rules/Visit/ProofOFDelivery/GetStopAttachmentMimeType.js",
	"UseExternalViewer": true,
	"Properties": {
		"Path": "{@odata.mediaReadLink}"
	}
}