{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "DeliveryUpdateEntity"
	},
	"OnFailure": "/LMD_MDKApp/Actions/MyVisit/DeliveryUpdateFailure.action",
	"OnSuccess": "/LMD_MDKApp/Actions/StartMyVisit/DeliveryQuantitySuccessMessage.action",
	"ValidationRule": "/LMD_MDKApp/Rules/Visit/Delivery/ValidateDeliveredQtyFromTruck.js",
	"Target": {
		"Service": "/LMD_MDKApp/Services/LMD_MA.service",
		"EntitySet": "DocumentItems",
		"ReadLink": "/LMD_MDKApp/Rules/Visit/Delivery/DeliveryUpdateEntity.js"
	},
	"Properties": {
		"DeliveredQuantity": "#Control:FCDeliveredQuantity/#Value",
		"DocumentID": "{DocumentID}",
		"DocumentCategory": "{DocumentCategory}"
	},
	"Headers": {
		"OfflineOData.TransactionID": "#Property:RouteUUID"
	}
}