{
	"_Type": "Action.Type.ODataService.ChangeSet",
	"ActionResult": {
		"_Name": "DocumentItemsChangeset"
	},
	"OnFailure": "/LMD_MDKApp/Actions/MyVisit/DocumentItemsFailure.action",
	"Target": {
		"Service": "/LMD_MDKApp/Services/LMD_MA.service"
	},
	"Actions": [
		"/LMD_MDKApp/Actions/MyVisit/DeliveryUpdateEntity.action"
	]
}