{
	"_Type": "Action.Type.ODataService.ChangeSet",
	"ActionResult": {
		"_Name": "DocumentChangeset"
	},
	"OnFailure": "/LMD_MDKApp/Actions/MyVisit/DocumentChangesetfailure.action",
	"OnSuccess": "/LMD_MDKApp/Actions/MyVisit/DocumentItemsChangeset.action",
	"Target": {
		"Service": "/LMD_MDKApp/Services/LMD_MA.service"
	},
	"Actions": [
		"/LMD_MDKApp/Actions/MyVisit/UpdateDeliveryDate.action"
	]
}