{
	"_Type": "Action.Type.ODataService.Read",
	"ActionResult": {
		"_Name": "ReadDocumentUUID"
	},
	"OnFailure": "/LMD_MDKApp/Actions/MyVisit/ReadDocumentFailure.action",
	"OnSuccess": "/LMD_MDKApp/Rules/Visit/ReadDocumentUUIDReadLink.js",
	"Target": {
		"Service": "/LMD_MDKApp/Services/LMD_MA.service",
		"EntitySet": "Documents",
		"QueryOptions": "/LMD_MDKApp/Rules/Main/GetRouteFilter.js"
	},
	"Properties": [
		"DocumentUUID",
		"RouteUUID",
		"StopUUID",
		"DocumentID",
		"DocumentCategory",
		"DeliveryDate",
		"IsReturn"
	]
}