{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "UpdateDeliveryDate"
	},
	"Target": {
		"Service": "/LMD_MDKApp/Services/DEST_SAMLMD_PPROP.service",
		"EntitySet": "Documents",
		"ReadLink": "{{#Property:ReadLink}}"
	},
	"Properties": {
		"DocumentID": "{{#Property:DocumentID}}",
		"DeliveryDate": "{{#Property:DeliveryDate}}"
	},
	"Headers": {
		"OfflineOData.TransactionID ": "#Property:RouteUUID"
	}
}