{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "UpdateDeliveryDate"
	},
	"Target": {
		"Service": "/LMD_MDKApp/Services/LMD_MA.service",
		"EntitySet": "Documents",
		"ReadLink": "{{#Property:ReadLink}}"
	},
	"Properties": {
		"DeliveryDate": "{{#Property:DeliveryDate}}"
	},
	"Headers": {
		"OfflineOData.TransactionID": "#Property:RouteUUID"
	},
	"RequestOptions": {
		"UpdateMode": "Merge"
	}
}