{
	"_Type": "Action.Type.ODataService.ChangeSet",
	"ActionResult": {
		"_Name": "COCIChangeSet"
	},
	"OnFailure": "/LMD_MDKApp/Actions/StartCheckin/COCI_Changset_Failure.action",
	"OnSuccess": "/LMD_MDKApp/Actions/StartCheckout/Checkout/TruckLoad/COCIProducts_Checkout_Changseset.action",
	"Target": {
		"Service": "/LMD_MDKApp/Services/LMD_MA.service"
	},
	"Actions": [
		"/LMD_MDKApp/Actions/StartCheckin/COCIProduct_Create_from_Stops.action",
		"/LMD_MDKApp/Actions/Reload_CheckIn/COCIProduct_Create_from_Stops.action"
	]
}