{
	"_Type": "Action.Type.ODataService.CreateRelatedEntity",
	"ActionResult": {
		"_Name": "CollectionClearings_Cash"
	},
	"OnFailure": "/LMD_MDKApp/Actions/MyVisit/Payment/Collection_Failure.action",
	"OnSuccess": "/LMD_MDKApp/Rules/Visit/Payment/CloseToVisit.js",
	"Target": {
		"Service": "/LMD_MDKApp/Services/LMD_MA.service",
		"EntitySet": "CollectionClearings"
	},
	"ParentLink": {
		"Target": {
			"EntitySet": "CollectionPayments",
			"ReadLink": "/LMD_MDKApp/Rules/Visit/Payment/Collection_Clearings_ReadLink.js"
		},
		"Property": "to_CollectionClearings"
	},
	"Properties": {
		"Amount": "/LMD_MDKApp/Rules/Visit/Payment/Get_CollectionPayment_Amount.js",
		"Currency": "/LMD_MDKApp/Rules/Visit/Payment/GetCollectionPaymentCurrency.js",
		"AssignmentType": "FIA",
		"OpenItemAmount": "/LMD_MDKApp/Rules/Visit/Payment/GetSelectedOpenItemAmount.js",
		"AccountingDocument": "/LMD_MDKApp/Rules/Visit/Payment/GetSelectedOpenItemAccountingDoc.js",
		"AccountingDocumentItem": "/LMD_MDKApp/Rules/Visit/Payment/GetSelectedOpenItemAccountingItem.js",
		"CompanyCode": "/LMD_MDKApp/Rules/Visit/Payment/GetSelectedOpenItemCompanyCode.js",
		"FiscalYear": "/LMD_MDKApp/Rules/Visit/Payment/GetSelectedOpenItemFiscalYear.js"
	},
	"Headers": {
		"OfflineOData.TransactionID": "#Property:RouteUUID"
	}
}