{
	"_Type": "Action.Type.ODataService.CreateRelatedEntity",
	"ActionResult": {
		"_Name": "CashPayment"
	},
	"OnSuccess": "/LMD_MDKApp/Actions/StartCheckin/Payment/CashPaymentMessage.action",
	"Target": {
		"Service": "/LMD_MDKApp/Services/LMD_MA.service",
		"EntitySet": "COCIPayments"
	},
	"ParentLink": {
		"Target": {
			"EntitySet": "Stops",
			"ReadLink": "/LMD_MDKApp/Rules/Checkin/Payment/COCI_Checkinpaymentreadlink.js"
		},
		"Property": "to_COCIPayments"
	},
	"Properties": {
		"PaymentType": "CA",
		"Currency": "{(clientData.Checkin_Currency)}",
		"Amount": "{(clientData.Checkin_Amount)}"
	},
	"Headers": {
		"OfflineOData.TransactionID": "#Property:RouteUUID"
	}
}
