{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "EndDateTime"
	},
	"Target": {
		"Service": "/LMD_MDKApp/Services/DEST_SAMSMA_PPROP.service",
		"EntitySet": "Routes",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"RouteUUID": "",
		"EndDateTime": "/LMD_MDKApp/Rules/Checkout/TruckInfo/GetLastChangeTimeStamp.js"
	}
}