{
	"_Type": "Action.Type.ODataService.Read",
	"ActionResult": {
		"_Name": "ReadRouteByUUID"
	},
	"OnFailure": "/LMD_MDKApp/Actions/Main/Routes/ReadlinkFailedforRouteStart.action",
	"OnSuccess": "/LMD_MDKApp/Rules/UpdateRouteUsingReadLink.js",
	"Target": {
		"Service": "/LMD_MDKApp/Services/DEST_SAMSMA_PPROP.service",
		"EntitySet": "Routes",
		"QueryOptions": "$filter=RouteUUID eq guid'{{#Property:RouteUUID}}'&$top=1"
	},
	"Properties": [
		"RouteUUID",
		"RouteID",
		"MainDriverID",
		"CoDriverID",
		"TrailerID",
		"TrailerLicensePlate",
		"VehicleID",
		"VehicleType",
		"LicensePlate",
		"RouteType",
		"OdometerBegin",
		"PlannedStartDateTime",
		"OdometerEnd",
		"PlannedEndDateTime",
		"StartDateTime",
		"EndDateTime",
		"Timezone",
		"OdometerUOM",
		"DepartureShippingPoint",
		"ArrivalShippingPoint",
		"ExecutionOrganization",
		"LastChangeTimestamp",
		"DepartureLocationID",
		"ArrivalLocationID",
		"CheckSumUploadedStops",
		"UploadType",
		"Currency"
	]
}