{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "StartDateTime"
	},
	"Target": {
		"Service": "/LMD_MDKApp/Services/DEST_SAMLMD_PPROP.service",
		"EntitySet": "Routes",
		"ReadLink": "{{#Property:routeReadLink}}"
	},
	"Properties": {
		"StartDateTime": "{{#Property:StartDateTime}}"
	},
	"Headers": {
		"OfflineOData.TransactionID": "#Property:RouteUUID"
	}
}