{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "StartDateTime"
	},
	"OnFailure": "/LMD_MDKApp/Actions/Main/Routes/RoutesStartDateTimeFailure.action",
	"Target": {
		"Service": "/LMD_MDKApp/Services/DEST_SAMSMA_PPROP.service",
		"EntitySet": "Routes",
		"ReadLink": "{{#Property:routeReadLink}}"
	},
	"Properties": {
		"StartDateTime": "{{#Property:StartDateTime}}"
	},
	"Headers": {
		"BatchGroup": "RouteStopBatch"
	}
}