{
	"_Type": "Action.Type.ProgressBanner",
	"OnSuccess": "/LMD_MDKApp/Actions/MD_BUSINESSPARTNER_SRV/Service/DownloadOffline.action",
	"Message": "Download in progress...",
	"CompletionMessage": "Download Successful",
	"CompletionTimeout": 7
}