{
	"_Type": "Action.Type.OfflineOData.Download",
	"ActionResult": {
		"_Name": "DownloadOffline"
	},
	"OnSuccess": "/LMD_MDKApp/Rules/MD_BUSINESSPARTNER_SRV/ErrorArchive_CheckForSyncError.js",
	"Service": "/LMD_MDKApp/Services/MD_BUSINESSPARTNER_SRV.service",
	"DefiningRequests": [
		{
			"Name": "C_BPEmailAddress",
			"Query": "C_BPEmailAddress",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "C_BPAddressValueHelp",
			"Query": "C_BPAddressValueHelp",
			"AutomaticallyRetrievesStreams": false
		}
	]
}