{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "ActualQuantityFailure"
	},
	"Message": "{#ActionResults:COCIProduct_Create_from_Stops/error}",
	"Title": "{Error}",
	"OKCaption": "Ok"
}