{
	"_Type": "Action.Type.ODataService.ChangeSet",
	"ActionResult": {
		"_Name": "COCICheckinPayment_Changeset"
	},
	"OnSuccess": "/LMD_MDKApp/Actions/MyVisit/Payment/Collection_and_Collection_Payment_Changeset.action",
	"Target": {
		"Service": "/LMD_MDKApp/Services/LMD_MA.service"
	},
	"Actions": [
		"/LMD_MDKApp/Actions/StartCheckin/Payment/COCIPayment_Checkin.action",
		"/LMD_MDKApp/Actions/StartCheckin/Payment/COCI_CheckPayment.action"
	]
}