{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "NavToMainPagefromCompleteCheckout"
	},
	"OnSuccess": "/LMD_MDKApp/Actions/StartCheckin/UpdateOdometerChangeSet.action",
	"PageToOpen": "/LMD_MDKApp/Pages/Main.page",
	"ClearHistory": true
}