{
	"_Type": "Action.Type.ODataService.ChangeSet",
	"ActionResult": {
		"_Name": "UpdateOdometerChangeSet"
	},
	"OnSuccess": "/LMD_MDKApp/Actions/Main/Stops/UpdateStopsChangeset.action",
	"Target": {
		"Service": "/LMD_MDKApp/Services/LMD_MA.service"
	},
	"Actions": [
		"/LMD_MDKApp/Actions/Main/Routes/StartDateTime.action",
		"/LMD_MDKApp/Actions/StartCheckout/UpdateOdometerBegin.action",
		"/LMD_MDKApp/Actions/StartCheckin/UpdateOdometerEnd.action",
		"/LMD_MDKApp/Actions/Main/Routes/EndDateTime.action"
	]
}