{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "UpdateOdometerEnd"
	},
	"OnFailure": "/LMD_MDKApp/Actions/StartCheckout/OdometerFailure.action",
	"OnSuccess": "/LMD_MDKApp/Rules/Checkin/CheckinTruckInfo/ConfirmCheckinTruckInfoAndNavigate.js",
	"Target": {
		"Service": "/LMD_MDKApp/Services/DEST_SAMLMD_PPROP.service",
		"EntitySet": "Routes",
		"ReadLink": "/LMD_MDKApp/Rules/Checkin/CheckinTruckInfo/UpdateOdometerEndReadLink.js"
	},
	"Properties": {
		"OdometerEnd": "{#Control:OdometerEndInput/#Value}"
	},
	"Headers": {
		"OfflineOData.TransactionID": "#Property:RouteUUID"
	}
}