{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "ContentCreation_Attachments"
	},
	"OnFailure": "/LMD_MDKApp/Actions/StartMyVisit/ProofOfDelivery/Failed.action",
	"OnSuccess": "/LMD_MDKApp/Actions/StartMyVisit/ProofOfDelivery/SuccessMessage.action",
	"Target": {
		"Service": "/LMD_MDKApp/Services/LMD_MA.service",
		"EntitySet": "Contents"
	},
	"Properties": {
		"MimeType": "/LMD_MDKApp/Rules/Visit/ProofOFDelivery/GetDisplayedAttachmentContentType.js",
		"FileName": "/LMD_MDKApp/Rules/Visit/ProofOFDelivery/GetDisplayedAttachmentFileName.js"
	},
	"Headers": {
		"OfflineOData.TransactionID": "#Property:RouteUUID"
	}
}