{
	"_Type": "Action.Type.ODataService.CreateRelatedEntity",
	"ActionResult": {
		"_Name": "ContentCreation"
	},
	"OnFailure": "/LMD_MDKApp/Actions/StartMyVisit/ProofOfDelivery/Failed.action",
	"OnSuccess": {
		"Name": "/LMD_MDKApp/Actions/StartMyVisit/ProofOfDelivery/SuccessMessage.action",
		"Properties": {
			"Message": "Content successfully created",
			"OKCaption": "OK"
		}
	},
	"Target": {
		"Service": "/LMD_MDKApp/Services/LMD_MA.service",
		"EntitySet": "Contents"
	},
	"ParentLink": {
		"Target": {
			"EntitySet": "Attachments",
			"ReadLink": "/LMD_MDKApp/Rules/Visit/ProofOFDelivery/GetRouteAttachmentReadLinkByDocument.js"
		},
		"Property": "to_Content"
	},
	"Properties": {
		"MimeType": "/LMD_MDKApp/Rules/Visit/ProofOFDelivery/GetDisplayedAttachmentContentType.js",
		"FileName": "/LMD_MDKApp/Rules/Visit/ProofOFDelivery/GetDisplayedAttachmentFileName.js"
	},
	"Headers": {
		"OfflineOData.TransactionID": "#Property:RouteUUID"
	}
}