{
	"_Type": "Action.Type.ODataService.CreateRelatedMedia",
	"ActionResult": {
		"_Name": "Content_MediaCreation"
	},
	"OnFailure": "/LMD_MDKApp/Actions/StartMyVisit/ProofOfDelivery/Failed.action",
	"OnSuccess": "/LMD_MDKApp/Rules/Visit/ProofOFDelivery/SetPODConfirmed.js",
	"Target": {
		"Service": "/LMD_MDKApp/Services/LMD_MA.service",
		"EntitySet": "Contents"
	},
	"IsOnlineRequest": true,
	"Media": "/LMD_MDKApp/Rules/Visit/ProofOFDelivery/GetDisplayedAttachmentMedia.js",
	"ParentLink": {
		"Target": {
			"EntitySet": "Attachments",
			"ReadLink": "/LMD_MDKApp/Rules/Visit/ProofOFDelivery/GetStopAttachmentReadLinkByDocument.js"
		},
		"Property": "to_Content"
	},
	"Properties": {
		"MimeType": "/LMD_MDKApp/Rules/Visit/ProofOFDelivery/GetDisplayedAttachmentContentType.js",
		"FileName": "/LMD_MDKApp/Rules/Visit/ProofOFDelivery/GetDisplayedAttachmentFileName.js"
	},
	"Headers": {
		"OfflineOData.TransactionID": "#Property:RouteUUID"
	}
}